### ISSUE TITLE
Brain MRI Segmentation

### ISSUE THREAD

**Issue by Zhenya97** [IbraDje/PFCM#2]
Hi, thank you for sharing. What should I change with these  codes if I want to segment such a brain MRI (181*217, bmp)which is shown as follow? Looking forward to your reply. Thanks.

![781](https://user-images.githubusercontent.com/48851898/75439863-913e4d80-5995-11ea-8cb9-1725f03ed052.png)

**Comment by IbraDje** [comment]
Hello there,
Sorry for the late reply.
if I understood your question correctly, you want to operate on gray scale images. In that case you should read the image such that the array shape would be like `H*W*1` (if the image is `H*W`, you should reshape it).

`import cv2`
`img = cv2.imread('path/to/image.bmp', cv2.IMREAD_GRAYSCALE)`
Reshape the image
`img = img.reshape(img.shape[0], img.shape[1], 1)`
Rest of the code in [demo2.py](https://github.com/IbraDje/PFCM/blob/master/demo2.py)...
