### ISSUE TITLE
Typo in equation for U update

### ISSUE THREAD

**Issue by kroegern1** [IbraDje/PFCM#3]
Equation 21 in the PFCM paper has an exponent of 2/(m-1) which SHOULD correspond to 2/(expo-1), but you have 2/(nc-1) in the code. I believe this is a typo in both the predict and pfcm functions.

**Comment by IbraDje** [comment]
Hello there,
Apologies for the late response as I rarely go back to this code.
Thank you for pointing out the error. I have corrected it !
